### ISSUE TITLE
Bad installation instruction in readme

### ISSUE THREAD

**Issue by opoupeney** [SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-components#231]
The document refers to the following instruction:

`yarn add @symphony/uitoolkit-components`

Which results in:

`[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@symphony%2fuitoolkit-components: Not found".`

The package is published under symphony-ui and not symphony. The correct instruction should be:

`yarn add @symphony-ui/uitoolkit-components`

**Comment by symphony-adnane** [comment]
Thanks @opoupeney , fixing it rn
