### ISSUE TITLE
[BUG] components/tooltip/Tooltip.tsx

### ISSUE THREAD

**Issue by BachLeFPT** [SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-components#280]
<TooltipContainer
            id={id}
            role="tooltip"
            ref={setPopperElement}
            className={classnames(
              type === 'tooltip' ? 'tk-tooltip' : 'tk-hint',
              **{ className } ==> it always is 'className' in HTML**
            )}
            style={styles.popper}
            {...attributes.popper}
            {...otherProps}
            onMouseEnter={() => handleMouseMove(true)}
            onMouseLeave={() => handleMouseMove(false)}
          >

**Comment by symphony-adnane** [comment]
Hello @BachLeFPT what's the issue here? how could we help ?

**Comment by BachLeFPT** [comment]
@symphony-adnane 
Problem is object in classnames: `{ className }` => always have class `className` in your html, it is not name of class which you pass from props(className)

=> `<div  class=".... className ..." >`

It should be `[className`] instead of `{className}`
(https://github.com/JedWatson/classnames)

```
<TooltipContainer
id={id}
role="tooltip"
ref={setPopperElement}
className={classnames(
type === 'tooltip' ? 'tk-tooltip' : 'tk-hint',
[className]
)}
style={styles.popper}
{...attributes.popper}
{...otherProps}
onMouseEnter={() => handleMouseMove(true)}
onMouseLeave={() => handleMouseMove(false)}
>
```
Thanks!
